AllowedHosts = "*"

[Serilog]
Using = [
  "Serilog.Sinks.Console",
  "Me.Xfox.ZhuiAnime",
  "Sentry.Serilog",
  "Serilog.Sinks.Grafana.Loki",
]

[Serilog.MinimumLevel]
Default = "Debug"
[Serilog.MinimumLevel.Override]
Microsoft = "Information"
"Microsoft.AspNetCore" = "Warning"
"Microsoft.EntityFrameworkCore.Database.Command" = "Warning"

[Serilog.WriteTo.Console]
Name = "Console"

[Serilog.Properties]
Application = "ZhuiAni.me"

[ConnectionStrings]
ZAContext = "Host=localhost;Database=zhuianime;Include Error Detail=true"

[Modules.TorrentDirectory]
IntervalBetweenFetch = 00:05:00
IntervalBetweenPages = 00:00:10
FetchPageThreshold = 20

[Modules.TorrentDirectory.Sources]
"bangumi.moe" = true
"acg.rip" = true
