root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "prettier"
  - "solid"
parserOptions:
  tsconfigRootDir: "."
  project: ["./tsconfig.json"]

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:solid/recommended"
  - "prettier"
  - "plugin:prettier/recommended"

ignorePatterns:
  - "vite.config.ts"
  - "tailwind.config.js"
  - "postcss.config.js"
