root: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - "react"
  - "react-hooks"
parserOptions:
  tsconfigRootDir: "."
  project: ["./tsconfig.json"]

extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"
  - "plugin:react/recommended"
  - "plugin:react-hooks/recommended"
  - "prettier"

ignorePatterns:
  - "vite.config.ts"

settings:
  react:
    version: "detect"

rules:
  "no-console": ["error", { allow: ["warn", "error"] }]
  "@typescript-eslint/no-unused-vars": ["error", { "varsIgnorePattern": "^_", "argsIgnorePattern": "^_" }]
